### ISSUE TITLE
Question for the script

### ISSUE THREAD

**Issue by Fukotaku** [luzifer-docker/space_engineers#1]
Hi, the script needs the game files or steamcmd.sh in the same folder?
Could you explain in detail the operation?
Thank you for your work.

**Comment by boistordu** [comment]
It seems that he doesn't want to explain things but just do things for him...

**Comment by Fukotaku** [comment]
Ok, sorry for this silly question.
I progressed since the last time but I was not successful, I am beginning on docker.
It's a script full install space engineers server ? or almost ?
Thank you for answering !

**Comment by Luzifer** [comment]
Hm interesting I didn't saw the initial issue… :(

I'm sorry this repository misled you but I wasn't able to get this running at all. So it never worked as it should and I gave up on this because another member of our group bought a Windows server and installed the game on that one.

I'll leave this repo for another day so you are able to read this answer and then throw it away as it is leftover crap which did not work at all… Sorry again for the trouble.

**Comment by Fukotaku** [comment]
No problem, thank you to prevent even though it's late.
I will not have to search long time ^^
